return {
  kind_icons = {
    Text = "",
    Method = "",
    Function = "",
    Constructor = "",
    Field = "",
    Variable = "",
    Class = "ﴯ",
    Interface = "",
    Module = "",
    Property = "ﰠ",
    Unit = "",
    Value = "",
    Enum = "",
    Keyword = "",
    Snippet = "",
    Color = "",
    File = "",
    Reference = "",
    Folder = "",
    EnumMember = "",
    Constant = "",
    Struct = "",
    Event = "",
    Operator = "",
    TypeParameter = "",
  },
  git = {
    branch = "",
    added = " ",
    modified = " ",
    removed = " ",
    unstaged = "✗",
    staged = "✔",
    unmerged = "",
    renamed = "➜",
    untracked = "",
    deleted = "⁃",
    ignored = "",
  },
  diagnostic = {
    Error = " ",
    Warn = " ",
    Hint = " ",
    Info = " ",
  },
  separator = {
    component_left = "",
    component_right = "",
    section_left = "",
    section_right = "",
  },
  folder = {
    arrow_closed = "",
    arrow_open = "",
    default = "",
    open = "",
    empty = "",
    empty_open = "",
    symlink = "",
    symlink_open = "",
  },
  tree = {
    symlink_arrow = " ➦ ",
    default = "",
    symlink = "",
    bookmark = "",
  },
}
