return {
  kind_icons = {
    Text = "",
    Method = "",
    Function = "",
    Constructor = "",
    Field = "",
    Variable = "",
    Class = "ﴯ",
    Interface = "",
    Module = "",
    Property = "ﰠ",
    Unit = "",
    Value = "",
    Enum = "",
    Keyword = "",
    Snippet = "",
    Color = "",
    File = "",
    Reference = "",
    Folder = "",
    EnumMember = "",
    Constant = "",
    Struct = "",
    Event = "",
    Operator = "",
    TypeParameter = "",
  },
  git = {
    branch = "",
    added = " ",
    modified = " ",
    removed = " ",
  },
  diagnostic = {
    Error = " ",
    Warn = " ",
    Hint = " ",
    Info = " ",
  },
  separator = {
    component_left = "",
    component_right = "",
    section_left = "",
    section_right = "",
  },
}
